spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hanghae_post
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rnaehfdl
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
jwt:
  secret:
    key: 1aqk7YyM66W07YOA7L2U65Sp7YG012+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==